layout: {zmk_keyboard: corne_c}
layers:
  default: [TAB, Q, W, E, R, T, Y, U, I, O, P, ESCAPE, LCTRL, A, S, D, F, G, H, J, K, L, ;, RETURN, LEFT ALT, Z, X, C, V, B, N, M, ',', ., /, RIGHT GUI, l_primer,
    LEFT SHIFT, SPACE, BACKSPACE, RSHIFT, r_primer]
  l_primer:
  - ''
  - ''
  - ''
  - ''
  - \
  - '-'
  - Sft+^
  - Sft+&
  - Sft+*
  - Sft+(
  - Sft+)
  - DEL
  - ESC
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - '='
  - media
  - F1
  - F2
  - F3
  - F4
  - F5
  - ''''
  - Sft+"
  - ''
  - ''
  - ''
  - F11
  - {type: held}
  - LALT
  - SPACE
  - SPACE
  - RALT
  - Sft+~
  r_primer:
  - '~'
  - Sft+!
  - Sft+@
  - Sft+#
  - Sft+$
  - Sft+%
  - Sft+_
  - +
  - Sft+|
  - ''
  - ''
  - ''
  - '`'
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - CAPS
  - F12
  - ''
  - '['
  - ']'
  - Sft+{
  - Sft+}
  - F6
  - F7
  - F8
  - F9
  - F10
  - media
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - ''
  - ''
  - ''
  - {type: held}
  media:
  - BRIGHTNESS INC
  - VOLUME UP
  - PREVIOUS
  - UP ARROW
  - NEXT
  - PAGE UP
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - {t: BT, h: '4'}
  - OUT TOG
  - BRIGHTNESS DEC
  - VOLUME DOWN
  - LEFT
  - DOWN
  - RIGHT
  - PAGE DOWN
  - LEFT ARROW
  - DOWN ARROW
  - UP ARROW
  - RIGHT ARROW
  - ''
  - ''
  - {type: held}
  - MUTE
  - HOME
  - PLAY PAUSE
  - END
  - INSERT
  - '&prev_desktop'
  - '&mkp LCLK'
  - '&mkp RCLK'
  - '&next_desktop'
  - ''
  - BT CLR
  - {type: held}
  - RIGHT GUI
  - PRINTSCREEN
  - ''
  - RIGHT GUI
  - ''
  '4':
  - ESCAPE
  - ''
  - ''
  - UP ARROW
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: default, h: toggle}
  - ''
  - A
  - LEFT ARROW
  - DOWN
  - RIGHT
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - S
  - D
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - SPACE
  - ''
  - ''
  - ''
  '5':
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: default, h: toggle}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  '6':
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: default, h: toggle}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
