manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  # Custom
  - name: sirzenith
    url-base: https://github.com/SirZenith

  projects:
  - name: zmk
    remote: zmkfirmware
    revision: main
    import: app/west.yml
  # Custom
  - name: nice-view-gem
    remote: sirzenith
    revision: main
  self:
    path: config
